server:
  port: 8080

### Database for MySQL ###
spring:
  datasource:
    database: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/bhge
    username: sa
    password:
    initialization-mode: embedded
    schema: classpath:db/schema.sql
  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2-console
      enabled: true


mybatis:
  typeAliasesPackage: org.canx.model
  mapperLocations: classpath:mapper/*.xml


# LOGGING
#logging:
#  level:
#    org.springframework.security: debug